name: Testify
description: All your files are become tests
theme: solarized-dark
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

# Octopress Settings
#Default extension for new posts and pages
post_ext: md
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft
